**1126 xtpoisson

gen compe_rate_minus1_adj = compe_rate_minus1

replace compe_rate_minus1_adj = 0 if compe_rate_minus1_adj < 0

xtset pres_pm_codes ele_t

** compe_rate_minus1_adj

xtpoisson compe_rate_minus1_adj lnsalary_am_kokuji, fe vce(robust) 

margins, dydx(lnsalary_am_kokuji)

xtpoisson compe_rate_minus1_adj lnsalary_am_kokuji ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_time_year ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index cand_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 n_staff_all, fe vce(robust) 

xtpoisson compe_rate_minus1_adj F1.lnsalary_am_kokuji lnsalary_am_kokuji ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_time_year ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index cand_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 n_staff_all, fe vce(robust)

xtpoisson compe_rate_minus1_adj F1.lnsalary_am_kokuji F2.lnsalary_am_kokuji lnsalary_am_kokuji ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_time_year ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index cand_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 n_staff_all, fe vce(robust)

xtreg compe_rate_minus1_adj F1.lnsalary_am_kokuji lnsalary_am_kokuji ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_time_year ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index cand_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 n_staff_all, fe vce(robust)



xtpoisson compe_rate_minus1_adj lnsalary_am_kokuji ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_time_year ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index cand_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 n_staff_all if ele_t > 2, fe vce(robust) 

xtpoisson compe_rate_minus1_adj lnsalary_am_kokuji ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_time_year ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index cand_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 n_staff_all if target_heisei_gappei == 0, fe vce(robust) 

xtpoisson compe_rate_minus1_adj lnsalary_am_kokuji ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_time_year ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index cand_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 n_staff_all if target_heisei_gappei == 1, fe vce(robust)

xtpoisson compe_rate_minus1_adj lnsalary_am_kokuji ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_time_year ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index cand_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 n_staff_all after_gappei, fe vce(robust)
 

** ratio_women_cand 

xtpoisson ratio_women_cand lnsalary_am_kokuji, fe vce(robust) 

xtpoisson ratio_women_cand lnsalary_am_kokuji ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_time_year ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index cand_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 n_staff_all, fe vce(robust) 

xtpoisson ratio_women_cand lnsalary_am_kokuji F1.lnsalary_am_kokuji ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_time_year ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index cand_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 n_staff_all, fe vce(robust) 

xtpoisson ratio_women_cand lnsalary_am_kokuji F1.lnsalary_am_kokuji F2.lnsalary_am_kokuji ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_time_year ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index cand_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 n_staff_all, fe vce(robust) 

