** replace variable
gen ln_staff_all = log(n_staff_all)
gen ln_n_seats = log(n_seats_adopt) 
*不採用
gen ln_zaiseiryoku = log(zaiseiryoku_index) 
gen ln_mean_ruiji_1yago = log(mean_salary_ruiji_1yago)




replace ln_income_per = log(income_per_syotokuwari_time)

replace ln_diff_salary = log(salary_12month) - log(income_per_syotokuwari_time)
replace ratio_salary = salary_12month/income_per_syotokuwari_time
replace persentage_salary = (salary_12month - income_per_syotokuwari_time)/income_per_syotokuwari_time

replace sigaika_ratio_area = 1 if sigaika_ratio_area > 1

xtset pres_pm_codes ele_t

xtsum compe_rate_adopt lnsalary_am_kokuji ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all

sum compe_rate_adopt lnsalary_am_kokuji ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all


** compe_rate_minus1_adj

poisson compe_rate_minus1_adj lnsalary_am_kokuji ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 n_staff_all, vce(robust)

xtpoisson compe_rate_minus1_adj lnsalary_am_kokuji ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 n_staff_all, fe vce(robust)

xtpoisson compe_rate_minus1_adj lnsalary_am_kokuji ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 n_staff_all i.nendo, fe vce(robust)

xtpoisson compe_rate_minus1_adj lnsalary_am_kokuji ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 n_staff_all i.nendo, fe vce(robust)

* remove ln_all_menseki
xtpoisson compe_rate_minus1_adj lnsalary_am_kokuji ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 n_staff_all i.nendo, fe vce(robust)

* remove ln_all_menseki sigaika_ratio_area
xtpoisson compe_rate_minus1_adj lnsalary_am_kokuji ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per canlive_ratio_menseki ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 n_staff_all i.nendo, fe vce(robust)

* remove ln_all_menseki sigaika_ratio_area canlive_ratio_menseki
xtpoisson compe_rate_minus1_adj lnsalary_am_kokuji ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 n_staff_all i.nendo, fe vce(robust)

*** →　あまり変わらない



** compe_rate_minus1

xtpoisson compe_rate_minus1 lnsalary_am_kokuji ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 n_staff_all i.nendo if compe_rate_minus1 >= 0, fe vce(robust)

xtpoisson compe_rate_minus1 lnsalary_am_kokuji ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 n_staff_all i.nendo if compe_rate_minus1 >= 0, fe vce(robust)

* remove sigaika_ratio_area
xtpoisson compe_rate_minus1 lnsalary_am_kokuji ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 n_staff_all i.nendo if compe_rate_minus1 >= 0, fe vce(robust)

* remove ln_all_menseki sigaika_ratio_area canlive_ratio_menseki
xtpoisson compe_rate_minus1 lnsalary_am_kokuji ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 n_staff_all i.nendo if compe_rate_minus1 >= 0, fe vce(robust)

*** →　あまり変わらない

** compe_rate_minus1_adj ~ ln_diff_salary

xtpoisson compe_rate_minus1_adj ln_diff_salary ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 n_staff_all i.nendo, fe vce(robust)
*** 点推定値マイナス

* interaction with win_ratio_musyozoku_pre

xtpoisson compe_rate_minus1_adj c.ln_diff_salary##c.win_ratio_musyozoku_pre ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 n_staff_all i.nendo, fe vce(robust)
margins, dydx(ln_diff_salary) at(win_ratio_musyozoku_pre = (0 0.2 0.4 0.6 0.8 1))
*** 有意にマイナス

xtpoisson compe_rate_minus1_adj c.ln_diff_salary##c.win_ratio_musyozoku_pre ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 n_staff_all i.nendo, fe vce(robust)
margins, dydx(ln_diff_salary) at(win_ratio_musyozoku_pre = (0 0.2 0.4 0.6 0.8 1))
*** 有意にマイナス



** compe_rate_adopt; FE

reg compe_rate_adopt lnsalary_am_kokuji ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 n_staff_all, vce(robust)

xtreg compe_rate_adopt lnsalary_am_kokuji ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 n_staff_all i.nendo, fe vce(robust)
*** compe_rate_minus1_adj よりは有意に出ない

* remove ln_all_menseki
xtreg compe_rate_adopt lnsalary_am_kokuji ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 n_staff_all i.nendo, fe vce(robust)

* remove ln_all_menseki　sigaika_ratio_area
xtreg compe_rate_adopt lnsalary_am_kokuji ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per canlive_ratio_menseki ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 n_staff_all i.nendo, fe vce(robust)

* remove ln_all_menseki　sigaika_ratio_area　canlive_ratio_menseki 
xtreg compe_rate_adopt lnsalary_am_kokuji ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 n_staff_all i.nendo, fe vce(robust)

*** →　あまり変わらない

** compe_rate_adopt; AB

** test of strictlly exogeoneity(remove win_ratio_musyozoku_pre)
xtreg compe_rate_adopt lnsalary_am_kokuji ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku  expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 n_staff_all i.nendo, fe vce(robust)

xtreg compe_rate_adopt lnsalary_am_kokuji F1.lnsalary_am_kokuji ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 n_staff_all i.nendo, fe vce(robust)

xtreg compe_rate_adopt lnsalary_am_kokuji F1.lnsalary_am_kokuji F2.lnsalary_am_kokuji ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku  expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 n_staff_all i.nendo, fe vce(robust)

test F1.lnsalary_am_kokuji F2.lnsalary_am_kokuji


* difference GMM without lag dep
xtabond2 compe_rate_adopt lnsalary_am_kokuji i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(lnsalary_am_kokuji) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) noleveleq robust twostep 
** 一応それっぽい結果（有意ではない）

* same as above; remove ln_all_menseki canlive_ratio_menseki sigaika_ratio_area
xtabond2 compe_rate_adopt lnsalary_am_kokuji i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per  ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(lnsalary_am_kokuji) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) noleveleq robust twostep 
 

*same;  passthru for strict iv
xtabond2 compe_rate_adopt lnsalary_am_kokuji i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(lnsalary_am_kokuji) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, passthru) noleveleq robust twostep
*** 点推定値マイナス

*same;  ln_mean_ruiji_1yago is included in gmmstyle iv 
xtabond2 compe_rate_adopt lnsalary_am_kokuji i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(lnsalary_am_kokuji ln_mean_ruiji_1yago) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) noleveleq robust twostep
*** 点推定値マイナス；　検定もアカン

* difference GMM with lag dep
xtabond2 compe_rate_adopt lnsalary_am_kokuji L1.compe_rate_adopt i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(lnsalary_am_kokuji L.compe_rate_adopt) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) noleveleq robust twostep
** 一応それっぽい結果（有意ではない）

*same;  passthru for strict iv
xtabond2 compe_rate_adopt lnsalary_am_kokuji L1.compe_rate_adopt i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(lnsalary_am_kokuji L.compe_rate_adopt) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, passthru) noleveleq robust twostep
*** 点推定値マイナス

*same;  ln_mean_ruiji_1yago is included in gmmstyle iv 
xtabond2 compe_rate_adopt lnsalary_am_kokuji L1.compe_rate_adopt i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(lnsalary_am_kokuji L.compe_rate_adopt ln_mean_ruiji_1yago) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) noleveleq robust twostep
** 点推定値マイナス；　検定もアカン


* system GMM without lag dep
xtabond2 compe_rate_adopt lnsalary_am_kokuji i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(lnsalary_am_kokuji) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, eq(both)) robust twostep 
*** 点推定値マイナス

xtabond2 compe_rate_adopt lnsalary_am_kokuji i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(lnsalary_am_kokuji) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, eq(both)) nocons robust twostep 
*** 点推定値マイナス

*same;  strict iv for only level eq
xtabond2 compe_rate_adopt lnsalary_am_kokuji i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(lnsalary_am_kokuji) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, eq(level)) robust twostep
*** 点推定値マイナス

xtabond2 compe_rate_adopt lnsalary_am_kokuji i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(lnsalary_am_kokuji) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, eq(level)) nocons robust twostep

*same;  ln_mean_ruiji_1yago is included in gmmstyle iv 
xtabond2 compe_rate_adopt lnsalary_am_kokuji i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(lnsalary_am_kokuji ln_mean_ruiji_1yago) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) robust twostep 
*** 点推定値マイナス

xtabond2 compe_rate_adopt lnsalary_am_kokuji i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(lnsalary_am_kokuji ln_mean_ruiji_1yago) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) nocons robust twostep
*** 点推定値マイナス

*same;  all level eq (for diff eq, gmmstyle ivs are not used)
xtabond2 compe_rate_adopt lnsalary_am_kokuji i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(lnsalary_am_kokuji, eq(level)) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) robust twostep 
*** 点推定値マイナス

xtabond2 compe_rate_adopt lnsalary_am_kokuji i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(lnsalary_am_kokuji, eq(level)) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) nocons robust twostep 
*** 点推定値マイナス




* system GMM with lag dep
xtabond2 compe_rate_adopt lnsalary_am_kokuji L1.compe_rate_adopt i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(lnsalary_am_kokuji L.compe_rate_adopt) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, eq(both)) robust twostep
*** 点推定値マイナス

xtabond2 compe_rate_adopt lnsalary_am_kokuji L1.compe_rate_adopt i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(lnsalary_am_kokuji L.compe_rate_adopt) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, eq(both)) nocons robust twostep

* same as above; remove ln_all_menseki canlive_ratio_menseki sigaika_ratio_area
xtabond2 compe_rate_adopt lnsalary_am_kokuji L1.compe_rate_adopt i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(lnsalary_am_kokuji L.compe_rate_adopt) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, eq(both)) nocons robust twostep
*** 点推定値マイナス

*same;  strict iv for only level eq
xtabond2 compe_rate_adopt lnsalary_am_kokuji L1.compe_rate_adopt i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(lnsalary_am_kokuji L.compe_rate_adopt) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, eq(level)) robust twostep
*** 点推定値マイナス

xtabond2 compe_rate_adopt lnsalary_am_kokuji L1.compe_rate_adopt i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(lnsalary_am_kokuji L.compe_rate_adopt) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, eq(level)) nocons robust twostep
*** 点推定値マイナス

*same;  ln_mean_ruiji_1yago is included in gmmstyle iv 
xtabond2 compe_rate_adopt lnsalary_am_kokuji L1.compe_rate_adopt i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(lnsalary_am_kokuji L.compe_rate_adopt ln_mean_ruiji_1yago) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) robust twostep

xtabond2 compe_rate_adopt lnsalary_am_kokuji L1.compe_rate_adopt i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(lnsalary_am_kokuji L.compe_rate_adopt ln_mean_ruiji_1yago) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) nocons robust twostep


*same;  all level eq (for diff eq, gmmstyle ivs are not used)
xtabond2 compe_rate_adopt lnsalary_am_kokuji L1.compe_rate_adopt i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(lnsalary_am_kokuji L.compe_rate_adopt, eq(level)) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) robust twostep

xtabond2 compe_rate_adopt lnsalary_am_kokuji L1.compe_rate_adopt i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(lnsalary_am_kokuji L.compe_rate_adopt, eq(level)) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) nocons robust twostep

* same as above; remove ln_all_menseki canlive_ratio_menseki sigaika_ratio_area
xtabond2 compe_rate_adopt lnsalary_am_kokuji L1.compe_rate_adopt i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(lnsalary_am_kokuji L.compe_rate_adopt, eq(level)) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per  ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) robust twostep
** 推定値・有意性はあまり変わらない



** compe_rate_adopt; ln_diff_salary is used as explanatory variable

** OLS

reg compe_rate_adopt ln_salary_am_kokuji ln_income_per ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, vce(robust) 

reg compe_rate_adopt ln_diff_salary ln_income_per ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, vce(robust) 

** Fixed effect

reg compe_rate_adopt ln_diff_salary ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 n_staff_all, vce(robust)

reg compe_rate_adopt ln_diff_salary ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 n_staff_all, vce(robust)
** プラス有意

xtreg compe_rate_adopt ln_diff_salary ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 n_staff_all i.nendo, fe vce(robust)
*** マイナス有意

xtreg compe_rate_adopt ln_diff_salary ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 n_staff_all i.nendo, fe vce(robust)
*** 点推定マイナス

xtreg compe_rate_adopt ln_salary_am_kokuji ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 n_staff_all i.nendo, fe vce(robust)


** test of strictlly exogeoneity

xtreg compe_rate_adopt ln_diff_salary ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 n_staff_all i.nendo, fe vce(robust)

xtreg compe_rate_adopt ln_diff_salary F1.ln_diff_salary ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 n_staff_all i.nendo, fe vce(robust)

*(remove win_ratio_musyozoku_pre)
xtreg compe_rate_adopt ln_diff_salary F1.ln_diff_salary F2.ln_diff_salary ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku  expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 n_staff_all i.nendo, fe vce(robust)

test F1.ln_diff_salary F2.ln_diff_salary

** difference GMM without lag dep

xtabond2 compe_rate_adopt ln_diff_salary i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(ln_diff_salary) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) noleveleq robust twostep 
** プラス有意

xtabond2 compe_rate_adopt ln_diff_salary i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(ln_diff_salary) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) noleveleq robust twostep 
** 点推定値マイナス


** difference GMM with lag dep

xtabond2 compe_rate_adopt ln_diff_salary L1.compe_rate_adopt i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(ln_diff_salary L.compe_rate_adopt) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) noleveleq robust twostep 
** プラス有意

xtabond2 compe_rate_adopt ln_diff_salary L1.compe_rate_adopt i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(ln_diff_salary L1.compe_rate_adopt) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) noleveleq robust twostep 
** 点推定値マイナス；　検定もアカンくさい

** system GMM without lag dep

xtabond2 compe_rate_adopt ln_diff_salary i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(ln_diff_salary ) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) robust twostep 
** 点推定プラス

xtabond2 compe_rate_adopt ln_diff_salary i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(ln_diff_salary L1.compe_rate_adopt) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) robust twostep 
** マイナス有意

xtabond2 compe_rate_adopt ln_diff_salary i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(ln_diff_salary,eq(level)) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) robust twostep 
** 点推定プラス

xtabond2 compe_rate_adopt ln_diff_salary i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(ln_diff_salary,eq(level)) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) noleveleq robust twostep 
** マイナス有意；　検定はアカンくさい　

corr ln_diff_salary ln_income_per
** →　相関は弱い、だけどln_income_per が無いモデルはomitted variable biasが存在する可能性あり


** system GMM with lag dep

xtabond2 compe_rate_adopt ln_diff_salary L1.compe_rate_adopt i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(ln_diff_salary L.compe_rate_adopt) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all)  robust twostep 
** 点推定プラス

xtabond2 compe_rate_adopt ln_diff_salary L1.compe_rate_adopt i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(ln_diff_salary L1.compe_rate_adopt) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) robust twostep 
** マイナス有意

xtabond2 compe_rate_adopt ln_diff_salary L1.compe_rate_adopt i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(ln_diff_salary L.compe_rate_adopt,eq(level)) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all)  robust twostep 
** 点推定プラス

xtabond2 compe_rate_adopt ln_diff_salary L1.compe_rate_adopt i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(ln_diff_salary L1.compe_rate_adopt,eq(level)) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) robust twostep
** マイナス有意

xtsum ln_diff_salary ln_income_per


** compe_rate_adopt; interaction term with 

xtreg compe_rate_adopt c.ln_diff_salary##c.ln_income_per ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 n_staff_all i.nendo, fe vce(robust)

xtreg compe_rate_adopt c.lnsalary_am_kokuji##c.ln_income_pe ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 n_staff_all i.nendo, fe vce(robust)

margins, dydx(lnsalary_am_kokuji) at(ln_income_pe = (7.5 8 8.5 9)) 
** 基本マイナス有意

xtreg compe_rate_adopt c.lnsalary_am_kokuji##c.ln_population ln_income_per n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 n_staff_all i.nendo, fe vce(robust)

margins, dydx(lnsalary_am_kokuji) at(ln_population = (5 7 9 11 13 15)) 
** 基本マイナス有意

xtreg compe_rate_adopt c.lnsalary_am_kokuji##c.win_ratio_musyozoku_pre ln_population ln_income_per n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 n_staff_all i.nendo, fe vce(robust)

margins, dydx(lnsalary_am_kokuji) at(win_ratio_musyozoku_pre = (0 0.2 0.4 0.6 0.8 1)) 
marginsplot
** 基本マイナス有意

xtreg compe_rate_adopt F(0/1)(c.lnsalary_am_kokuji##c.win_ratio_musyozoku_pre) ln_population ln_income_per n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 n_staff_all i.nendo, fe vce(robust)

margins, dydx(lnsalary_am_kokuji) at(win_ratio_musyozoku_pre = (0 0.2 0.4 0.6 0.8 1)) 
marginsplot
** 基本マイナス有意

** difference GMM without lag dep

xtabond2 compe_rate_adopt c.ln_diff_salary##c.ln_income_per i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(c.ln_diff_salary c.ln_diff_salary#c.ln_income_per) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) noleveleq robust twostep 

margins, dydx(ln_diff_salary) at(ln_income_pe = (7.5 8 8.5 9)) 
** 点推定だいたいプラス

xtabond2 compe_rate_adopt c.lnsalary_am_kokuji##c.ln_income_per i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(c.lnsalary_am_kokuji c.lnsalary_am_kokuji#c.ln_income_per) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) noleveleq robust twostep 

margins, dydx(lnsalary_am_kokuji) at(ln_income_per = (7.5 8 8.5 9)) 
** 点推定だいたいマイナスかつなんか変

xtabond2 compe_rate_adopt c.lnsalary_am_kokuji##c.ln_population ln_income_per i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(c.lnsalary_am_kokuji c.lnsalary_am_kokuji#c.ln_population) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) noleveleq robust twostep 

margins, dydx(lnsalary_am_kokuji) at(ln_population = (5 7 9 11 13 15)) 
** 有意（人口によって変動）
marginsplot

xtabond2 compe_rate_adopt c.lnsalary_am_kokuji##c.win_ratio_musyozoku_pre ln_population ln_income_per i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(c.lnsalary_am_kokuji c.lnsalary_am_kokuji#c.win_ratio_musyozoku_pre) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) noleveleq robust twostep 

margins, dydx(lnsalary_am_kokuji) at(win_ratio_musyozoku_pre = (0 0.2 0.4 0.6 0.8 1)) 
marginsplot
** 無所属割合1のときのみ有意(p=.06), 現状一番理論と整合的

xtabond2 compe_rate_adopt c.ln_diff_salary##c.win_ratio_musyozoku_pre ln_population ln_income_per i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(c.ln_diff_salary c.ln_diff_salary#c.win_ratio_musyozoku_pre) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) noleveleq robust twostep 

margins, dydx(ln_diff_salary) at(win_ratio_musyozoku_pre = (0 0.2 0.4 0.6 0.8 1)) 
marginsplot
** 無所属割合1のときのみ有意(p=.015), 現状一番理論と整合的

** 無所属割合; further estimator

** difference GMM without lag dep
xtabond2 compe_rate_adopt c.ln_diff_salary##c.win_ratio_musyozoku_pre ln_population ln_income_per i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(c.ln_diff_salary c.ln_diff_salary#c.win_ratio_musyozoku_pre) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) noleveleq robust twostep 
margins, dydx(ln_diff_salary) at(win_ratio_musyozoku_pre = (0 0.2 0.4 0.6 0.8 1)) 
** 後半有意

** difference GMM with lag dep
xtabond2 compe_rate_adopt c.ln_diff_salary##c.win_ratio_musyozoku_pre L1.compe_rate_adopt ln_population ln_income_per i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(c.ln_diff_salary c.ln_diff_salary#c.win_ratio_musyozoku_pre L.compe_rate_adopt) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) noleveleq robust twostep 
margins, dydx(ln_diff_salary) at(win_ratio_musyozoku_pre = (0 0.2 0.4 0.6 0.8 1))
** 後半有意; efficiency 向上

** system GMM without lag dep
xtabond2 compe_rate_adopt c.ln_diff_salary##c.win_ratio_musyozoku_pre ln_population ln_income_per i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(c.ln_diff_salary c.ln_diff_salary#c.win_ratio_musyozoku_pre) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) robust twostep 
margins, dydx(ln_diff_salary) at(win_ratio_musyozoku_pre = (0 0.2 0.4 0.6 0.8 1))
** 有意でない

xtabond2 compe_rate_adopt c.ln_diff_salary##c.win_ratio_musyozoku_pre ln_population ln_income_per i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(c.ln_diff_salary c.ln_diff_salary#c.win_ratio_musyozoku_pre,eq(level)) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) robust twostep 
margins, dydx(ln_diff_salary) at(win_ratio_musyozoku_pre = (0 0.2 0.4 0.6 0.8 1))
** 有意でない

** system GMM with lag dep
xtabond2 compe_rate_adopt c.ln_diff_salary##c.win_ratio_musyozoku_pre L1.compe_rate_adopt ln_population ln_income_per i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(c.ln_diff_salary c.ln_diff_salary#c.win_ratio_musyozoku_pre L.compe_rate_adopt) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) robust twostep 
margins, dydx(ln_diff_salary) at(win_ratio_musyozoku_pre = (0 0.2 0.4 0.6 0.8 1))
** 有意でない

** system GMM with lag dep
xtabond2 compe_rate_adopt c.ln_diff_salary##c.win_ratio_musyozoku_pre L1.compe_rate_adopt ln_population ln_income_per i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(c.ln_diff_salary c.ln_diff_salary#c.win_ratio_musyozoku_pre L.compe_rate_adopt,eq(level)) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) robust twostep 
margins, dydx(ln_diff_salary) at(win_ratio_musyozoku_pre = (0 0.2 0.4 0.6 0.8 1))
** 有意でない


** 市町村別
encode time_muni_kind, generate(muni_type)

xtreg compe_rate_adopt c.ln_diff_salary##i.muni_type ln_income_per ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 n_staff_all i.nendo, fe vce(robust)

xtreg compe_rate_adopt c.lnsalary_am_kokuji##i.muni_type ln_income_per ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 n_staff_all i.nendo, fe vce(robust)
margins, dydx(lnsalary_am_kokuji) at(muni_type = ) 

** esttab

estimates clear
** 保存内容をクリア

* Pooled　OLS (モデル1)
quietly reg compe_rate_adopt lnsalary_am_kokuji, vce(cluster pres_pm_codes)
estimates store r1, title("OLS")

** 推定結果を ｒ１ として保存、タイトルは　"OLS"
** (quietly は推定結果を表示しないコマンド)

estadd local municipality "No": r1
estadd local year "No": r1

** r1 に固定効果の情報を　municipality, year として保存、今回は両方とも NO

* Pooled　OLS (モデル２)
quietly reg compe_rate_adopt lnsalary_am_kokuji ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre ln_staff_all expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019, vce(cluster pres_pm_codes)
estimates store r2, title("OLS")

estadd local municipality "No": r2
estadd local year "No": r2

* Fixed　Effect (モデル1)
quietly xtreg compe_rate_adopt lnsalary_am_kokuji i.nendo, fe vce(cluster pres_pm_codes)
estimates store r3, title("FE")

estadd local municipality "Yes": r3
estadd local year "Yes": r3

* Fixed　Effect (モデル2)
quietly xtreg compe_rate_adopt lnsalary_am_kokuji ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_zaiseiryoku win_ratio_musyozoku_pre ln_staff_all expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 i.nendo, fe vce(cluster pres_pm_codes)
estimates store r4, title("FE")

estadd local municipality "Yes": r4
estadd local year "Yes": r4


* Fixed　Effect (モデル3)
quietly xtreg compe_rate_adopt lnsalary_am_kokuji ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre ln_staff_all expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 i.nendo, fe vce(cluster pres_pm_codes)
estimates store r5, title("FE")

estadd local municipality "Yes": r5
estadd local year "Yes": r5


* esttab を使って推定結果を表として表示
esttab r1 r2 r3 r4 r5, b(3) se(3) star(* 0.10 ** 0.05 *** 0.01) drop(touitsu_2007 *.nendo _cons) stats(year municipality N, fmt(%9.0f %9.0f %9.3f %9.0f) labels("Fiscal Year FE" "Municipality FE" "N")) 


* esttab の表を latex に出力
** english
esttab r1 r2 r3 r4 r5 using "compe_fe.tex", replace ///
b(3) se(3) star(* 0.10 ** 0.05 *** 0.01) booktabs ///
drop(touitsu_2007 *.nendo _cons) ///
stats(year municipality r2_a N, fmt(%9.0f %9.0f %9.3f %9.0f) labels("Fiscal Year FE" "Municipality FE" "Adj. \$R^2\$" "N")) ///
label nolz varwidth(16) modelwidth(13) style(tex)  ///
title(REGRESSION RESULT) coeflabels(lnsalary_am_kokuji "\$\log salary\$" ln_population "\$\log pupulation\$" n_seats_adopt "\$n \,seats\$" ///
population_elderly75_ratio "\$ratio\,over\,75\$" population_child15_ratio "\$ratio\,under\,15\$" ln_income_per "\$\log income\,per\,taxpayer\$" ///
ln_all_menseki "\$\log area\$" canlive_ratio_menseki "\$ratio\,habitable\$" sigaika_ratio_area "\$ratio\,urbanization\$" ln_zaiseiryoku ///
"\$\log financial\,index\$" win_ratio_musyozoku_pre "\$ratio\,independent\,winner_{t-1}\$" ln_staff_all "\$\log n\,staff\$" expired_dummy ///
"\$term\,expired\$"  touitsu_2011 "\$nationalwide\,2011\$" touitsu_2015 "\$nationalwide\,2015\$" touitsu_2019 "\$nationalwide\,2019\$") ///
mlabels(, span prefix(\multicolumn{@span}{c}{) suffix(})) ///
prehead("\documentclass[11pt]{article}" "\pagestyle{empty}" "\usepackage{booktabs}""\usepackage{siunitx}""\usepackage{lscape}" ///
"\usepackage[margin=20truemm]{geometry}""\sisetup{input-symbols = ()}""\begin{document}""\begin{table}\caption{@title}" ///
"\def\sym#1{\ifmmode^{#1}\else\(^{#1}\)\fi}""\begin{center}" ///
"\sisetup{table-space-text-post = \sym{***}}""\begin{tabular}{l*{@M}{llll}}""\toprule") posthead(\midrule) prefoot(\midrule) ///
postfoot("\bottomrule""\small\textit{Note:}""\end{tabular}""\end{center}""\end{table}""\end{document}")

esttab r1 r2 r3 r4 r5 using "compe_fe_jp.tex", replace ///
b(3) se(3) star(* 0.10 ** 0.05 *** 0.01) booktabs ///
drop(touitsu_2007 *.nendo _cons) nogaps ///
stats(year municipality r2_a N, fmt(%9.0f %9.0f %9.3f %9.0f) labels("年度固定効果" "自治体固定効果" "調整済み決定係数" "観測数")) ///
label nolz varwidth(16) modelwidth(13) style(tex)  ///
title(被説明変数: 1議席あたり立候補人数) coeflabels(lnsalary_am_kokuji "対数議員報酬額" ln_population "対数人口" n_seats_adopt "議席数" ///
population_elderly75_ratio "全人口に占める75歳以上の割合" population_child15_ratio "全人口に占める15歳未満の割合" ln_income_per "納税者1人あたり課税対象所得" ///
ln_all_menseki "対数面積" canlive_ratio_menseki "可住地面積割合" sigaika_ratio_area "市街化区域面積割合" ln_zaiseiryoku ///
"対数財政力指数" win_ratio_musyozoku_pre "前回当選者に占める無所属の割合" ln_staff_all "対数自治体職員数" expired_dummy ///
"任期満了ダミー"  touitsu_2011 "2011年統一選ダミー" touitsu_2015 "2015年統一選ダミー" touitsu_2019 "2019年統一選ダミー") ///
mlabels(, span prefix(\multicolumn{@span}{c}{) suffix(})) ///
prehead("\documentclass[11pt]{jsarticle}" "\pagestyle{empty}" "\usepackage{booktabs}""\usepackage{siunitx}""\usepackage{lscape}" ///
"\usepackage[margin=20truemm]{geometry}""\sisetup{input-symbols = ()}""\begin{document}""\begin{table}\caption{@title}" ///
"\def\sym#1{\ifmmode^{#1}\else\(^{#1}\)\fi}""\begin{center}" ///
"\sisetup{table-space-text-post = \sym{***}}""\begin{tabular}{l*{@M}{llll}}""\toprule") posthead(\midrule) prefoot(\midrule) ///
postfoot("\bottomrule""\small\textit{Note:}""\end{tabular}""\end{center}""\end{table}""\end{document}")

** ppml
estimates clear
** 保存内容をクリア

* 2SRI 1st stage; pooled
reg lnsalary_am_kokuji ln_mean_ruiji_1yago ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre ln_staff_all expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019, vce(cluster pres_pm_codes)

predict u_hat_1st, residuals

* 2SRI 1st stage; FE
xtreg lnsalary_am_kokuji ln_mean_ruiji_1yago ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre ln_staff_all expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 i.nendo, vce(cluster pres_pm_codes)

predict xt_u_hat_1st, e

**
poisson compe_rate_minus1_adj lnsalary_am_kokuji, vce(cluster pres_pm_codes)
estimates store r1, title("PPML")
estadd local municipality "No": r1
estadd local year "No": r1

margins, dydx(lnsalary_am_kokuji)

poisson compe_rate_minus1_adj lnsalary_am_kokuji ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre ln_staff_all expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 , vce(cluster pres_pm_codes)
estimates store r2, title("PPML")
estadd local municipality "No": r2
estadd local year "No": r2

margins, dydx(lnsalary_am_kokuji)

xtpoisson compe_rate_minus1_adj lnsalary_am_kokuji i.nendo, fe vce(robust)
estimates store r3, title("PPMLFE")
estadd local municipality "Yes": r3
estadd local year "Yes": r3

margins, dydx(lnsalary_am_kokuji) predict(nu0)

xtpoisson compe_rate_minus1_adj lnsalary_am_kokuji ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre ln_staff_all expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 i.nendo, fe vce(robust)
estimates store r4, title("PPMLFE")


estadd local municipality "Yes": r4
estadd local year "Yes": r4

margins, dydx(lnsalary_am_kokuji) predict(nu0)

poisson compe_rate_minus1_adj lnsalary_am_kokuji u_hat_1st ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre ln_staff_all expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019, vce(cluster pres_pm_codes)
estimates store r5, title("2SRI")
estadd local municipality "No": r5
estadd local year "No": r5

margins, dydx(lnsalary_am_kokuji)

xtpoisson compe_rate_minus1_adj lnsalary_am_kokuji xt_u_hat_1st ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre ln_staff_all expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 i.nendo, fe vce(robust)
estimates store r6, title("2SRIFE")
estadd local municipality "Yes": r6
estadd local year "Yes": r6

margins, dydx(lnsalary_am_kokuji) predict(nu0)

esttab r1 r2 r3 r4 r5 r6 using "compe_ppml_jp.tex", replace ///
b(3) se(3) star(* 0.10 ** 0.05 *** 0.01) booktabs ///
drop(touitsu_2007 *.nendo _cons) nogaps ///
stats(year municipality N, fmt(%9.0f %9.0f %9.3f %9.0f) labels("年度固定効果" "自治体固定効果" "観測数")) ///
label nolz varwidth(16) modelwidth(13) style(tex)  ///
title(被説明変数: 調整済み1議席あたり立候補人数) coeflabels(lnsalary_am_kokuji "対数議員報酬額" u_hat_1st "第1段階残差"　xt_u_hat_1st "第1段階残差(FE)" ///
ln_population "対数人口" n_seats_adopt "議席数" ///
population_elderly75_ratio "全人口に占める75歳以上の割合" population_child15_ratio "全人口に占める15歳未満の割合" ln_income_per "納税者1人あたり課税対象所得" ///
ln_all_menseki "対数面積" canlive_ratio_menseki "可住地面積割合" sigaika_ratio_area "市街化区域面積割合" ln_zaiseiryoku ///
"対数財政力指数" win_ratio_musyozoku_pre "前回当選者に占める無所属の割合" ln_staff_all "対数自治体職員数" expired_dummy ///
"任期満了ダミー"  touitsu_2011 "2011年統一選ダミー" touitsu_2015 "2015年統一選ダミー" touitsu_2019 "2019年統一選ダミー") ///
mlabels(, span prefix(\multicolumn{@span}{c}{) suffix(})) ///
prehead("\documentclass[10pt]{jsarticle}" "\pagestyle{empty}" "\usepackage{booktabs}""\usepackage{siunitx}""\usepackage{lscape}" ///
"\usepackage[margin=20truemm]{geometry}""\sisetup{input-symbols = ()}""\begin{document}""\begin{table}\caption{@title}" ///
"\def\sym#1{\ifmmode^{#1}\else\(^{#1}\)\fi}""\begin{center}" ///
"\sisetup{table-space-text-post = \sym{***}}""\begin{tabular}{l*{@M}{llll}}""\toprule") posthead(\midrule) prefoot(\midrule) ///
postfoot("\bottomrule""\end{tabular}""\end{center}""\end{table}""\end{document}")


*** FDIV

estimates clear

ivregress 2sls D.compe_rate_adopt (D.lnsalary_am_kokuji = L1.lnsalary_am_kokuji) D.(ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 nendo1 nendo2 nendo3 nendo4 nendo5 nendo6 nendo7 nendo8 nendo9 nendo10 nendo11 nendo12 nendo13 nendo14 nendo15), nocons vce(cluster pres_pm_codes)
estimates store r1, title("AH")
estadd local municipality "Yes": r1
estadd local year "Yes": r1

ivregress 2sls D.compe_rate_adopt (D.lnsalary_am_kokuji = L1.lnsalary_am_kokuji) D.(ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 nendo1 nendo2 nendo3 nendo4 nendo5 nendo6 nendo7 nendo8 nendo9 nendo10 nendo11 nendo12 nendo13 nendo14 nendo15), vce(cluster pres_pm_codes) 

ivregress 2sls D.compe_rate_adopt (D.lnsalary_am_kokuji LD.compe_rate_adopt = L1.lnsalary_am_kokuji L2.compe_rate_adopt) D.(ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 nendo1 nendo2 nendo3 nendo4 nendo5 nendo6 nendo7 nendo8 nendo9 nendo10 nendo11 nendo12 nendo13 nendo14 nendo15), nocons first vce(cluster pres_pm_codes)
estimates store r2, title("AH")
estadd local municipality "Yes": r2
estadd local year "Yes": r2

ivregress 2sls D.compe_rate_adopt (D.lnsalary_am_kokuji LD.compe_rate_adopt = L1.lnsalary_am_kokuji L2.compe_rate_adopt) D.(ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 nendo1 nendo2 nendo3 nendo4 nendo5 nendo6 nendo7 nendo8 nendo9 nendo10 nendo11 nendo12 nendo13 nendo14 nendo15), vce(cluster pres_pm_codes)

ivregress 2sls D.compe_rate_adopt (D.ln_diff_salary = L1.ln_diff_salary) D.(ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 nendo1 nendo2 nendo3 nendo4 nendo5 nendo6 nendo7 nendo8 nendo9 nendo10 nendo11 nendo12 nendo13 nendo14 nendo15), nocons vce(cluster pres_pm_codes)
estimates store r3, title("AH")
estadd local municipality "Yes": r3
estadd local year "Yes": r3

ivregress 2sls D.compe_rate_adopt (D.ln_diff_salary = L1.ln_diff_salary) D.(ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 nendo1 nendo2 nendo3 nendo4 nendo5 nendo6 nendo7 nendo8 nendo9 nendo10 nendo11 nendo12 nendo13 nendo14 nendo15), vce(cluster pres_pm_codes)

ivregress 2sls D.compe_rate_adopt (D.ln_diff_salary LD.compe_rate_adopt = L1.ln_diff_salary L2.compe_rate_adopt) D.(ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 nendo1 nendo2 nendo3 nendo4 nendo5 nendo6 nendo7 nendo8 nendo9 nendo10 nendo11 nendo12 nendo13 nendo14 nendo15), nocons vce(cluster pres_pm_codes)
estimates store r4, title("AH")
estadd local municipality "Yes": r4
estadd local year "Yes": r4

ivregress 2sls D.compe_rate_adopt (D.ln_diff_salary LD.compe_rate_adopt = L1.ln_diff_salary L2.compe_rate_adopt) D.(ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 nendo1 nendo2 nendo3 nendo4 nendo5 nendo6 nendo7 nendo8 nendo9 nendo10 nendo11 nendo12 nendo13 nendo14 nendo15), vce(cluster pres_pm_codes)

ivregress 2sls D.compe_rate_adopt (D.lnsalary_am_kokuji = ln_mean_ruiji_1yago) D.(ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 nendo1 nendo2 nendo3 nendo4 nendo5 nendo6 nendo7 nendo8 nendo9 nendo10 nendo11 nendo12 nendo13 nendo14 nendo15), nocons vce(cluster pres_pm_codes) 

ivregress 2sls D.compe_rate_adopt (D.lnsalary_am_kokuji = L1.ln_mean_ruiji_1yago) D.(ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 nendo1 nendo2 nendo3 nendo4 nendo5 nendo6 nendo7 nendo8 nendo9 nendo10 nendo11 nendo12 nendo13 nendo14 nendo15), vce(cluster pres_pm_codes) 


ivregress 2sls D.compe_rate_adopt (D.lnsalary_am_kokuji LD.compe_rate_adopt = L1.ln_mean_ruiji_1yago L2.compe_rate_adopt) D.(ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 nendo1 nendo2 nendo3 nendo4 nendo5 nendo6 nendo7 nendo8 nendo9 nendo10 nendo11 nendo12 nendo13 nendo14 nendo15), nocons vce(cluster pres_pm_codes)

ivregress 2sls D.compe_rate_adopt (D.lnsalary_am_kokuji LD.compe_rate_adopt = L1.ln_mean_ruiji_1yago L2.compe_rate_adopt) D.(ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 nendo1 nendo2 nendo3 nendo4 nendo5 nendo6 nendo7 nendo8 nendo9 nendo10 nendo11 nendo12 nendo13 nendo14 nendo15), vce(cluster pres_pm_codes)

esttab r1 r2 r3 r4 using "compe_fdiv_jp.tex", replace ///
b(3) se(3) star(* 0.10 ** 0.05 *** 0.01) booktabs ///
keep(D.lnsalary_am_kokuji D.ln_diff_salary LD.compe_rate_adopt D.ln_population D.n_seats_adopt D.population_elderly75_ratio D.population_child15_ratio ///
D.ln_income_per D.ln_all_menseki D.canlive_ratio_menseki D.sigaika_ratio_area D.ln_zaiseiryoku D.win_ratio_musyozoku_pre D.expired_dummy D.touitsu_2011 ///
D.touitsu_2015 D.touitsu_2019) nogaps ///
stats(year municipality N, fmt(%9.0f %9.0f %9.0f) labels("年度固定効果" "自治体固定効果" "観測数")) ///
label nolz varwidth(16) modelwidth(13) style(tex)  ///
title(被説明変数: 1議席あたり立候補人数) coeflabels(D.lnsalary_am_kokuji "対数議員報酬額" D.ln_diff_salary "報酬額対数差分" ///
LD.compe_rate_adopt "1議席あたり立候補人数_1期ラグ" D.ln_population "対数人口" D.n_seats_adopt "議席数" ///
D.population_elderly75_ratio "全人口に占める75歳以上の割合" D.population_child15_ratio "全人口に占める15歳未満の割合" D.ln_income_per "納税者1人あたり課税対象所得" ///
D.ln_all_menseki "対数面積" D.canlive_ratio_menseki "可住地面積割合" D.sigaika_ratio_area "市街化区域面積割合" D.ln_zaiseiryoku ///
"対数財政力指数" D.win_ratio_musyozoku_pre "前回当選者に占める無所属の割合" D.ln_staff_all "対数自治体職員数" D.expired_dummy ///
"任期満了ダミー"  D.touitsu_2011 "2011年統一選ダミー" D.touitsu_2015 "2015年統一選ダミー" D.touitsu_2019 "2019年統一選ダミー") ///
order(D.lnsalary_am_kokuji D.ln_diff_salary LD.compe_rate_adopt) ///
mlabels(, span prefix(\multicolumn{@span}{c}{) suffix(})) ///
prehead("\documentclass[10pt]{jsarticle}" "\pagestyle{empty}" "\usepackage{booktabs}""\usepackage{siunitx}""\usepackage{lscape}" ///
"\usepackage[margin=20truemm]{geometry}""\sisetup{input-symbols = ()}""\begin{document}""\begin{table}\caption{@title}" ///
"\def\sym#1{\ifmmode^{#1}\else\(^{#1}\)\fi}""\begin{center}" ///
"\sisetup{table-space-text-post = \sym{***}}""\begin{tabular}{l*{@M}{llll}}""\toprule") posthead(\midrule) prefoot(\midrule) ///
postfoot("\bottomrule""\end{tabular}""\end{center}""\end{table}""\end{document}")

estimates replay r1
estat first

ivreg2 D.compe_rate_adopt (D.lnsalary_am_kokuji LD.compe_rate_adopt = L1.lnsalary_am_kokuji L2.compe_rate_adopt) D.(ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 nendo1 nendo2 nendo3 nendo4 nendo5 nendo6 nendo7 nendo8 nendo9 nendo10 nendo11 nendo12 nendo13 nendo14 nendo15), nocons first cluster(pres_pm_codes)

ivreg2 D.compe_rate_adopt (D.ln_diff_salary LD.compe_rate_adopt = L1.ln_diff_salary L2.compe_rate_adopt) D.(ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 nendo1 nendo2 nendo3 nendo4 nendo5 nendo6 nendo7 nendo8 nendo9 nendo10 nendo11 nendo12 nendo13 nendo14 nendo15), nocons first cluster(pres_pm_codes)

ivreg2 D.compe_rate_adopt (D.ln_diff_salary  = L1.ln_diff_salary) D.(ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 nendo1 nendo2 nendo3 nendo4 nendo5 nendo6 nendo7 nendo8 nendo9 nendo10 nendo11 nendo12 nendo13 nendo14 nendo15), nocons first cluster(pres_pm_codes)


** diff GMM

estimates clear

* difference GMM without lag dep; lnsalary_am_kokuji
xtabond2 compe_rate_adopt lnsalary_am_kokuji i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(lnsalary_am_kokuji) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) noleveleq robust twostep 
estimates store r1, title("diff GMM")
estadd local municipality "Yes": r1
estadd local year "Yes": r1

* difference GMM with lag dep; lnsalary_am_kokuji
xtabond2 compe_rate_adopt lnsalary_am_kokuji L1.compe_rate_adopt i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(lnsalary_am_kokuji L.compe_rate_adopt) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) noleveleq robust twostep
estimates store r2, title("diff GMM")
estadd local municipality "Yes": r2
estadd local year "Yes": r2

** Interaction
xtabond2 compe_rate_adopt c.lnsalary_am_kokuji##c.win_ratio_musyozoku_pre L1.compe_rate_adopt ln_population ln_income_per i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(c.lnsalary_am_kokuji c.lnsalary_am_kokuji#c.win_ratio_musyozoku_pre L.compe_rate_adopt) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) noleveleq robust twostep 
estimates store r3, title("diff GMM")
estadd local municipality "Yes": r3
estadd local year "Yes": r3

margins, dydx(lnsalary_am_kokuji) at(win_ratio_musyozoku_pre = (0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1))
marginsplot
** 後半有意; efficiency 向上


** difference GMM without lag dep; lndiff_am_kokuji

xtabond2 compe_rate_adopt ln_diff_salary i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(ln_diff_salary) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) noleveleq robust twostep
estimates store r4, title("diff GMM")
estadd local municipality "Yes": r4
estadd local year "Yes": r4
** プラス有意

** difference GMM with lag dep; lndiff_am_kokuji
xtabond2 compe_rate_adopt ln_diff_salary L1.compe_rate_adopt i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(ln_diff_salary L.compe_rate_adopt) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) noleveleq robust twostep 
estimates store r5, title("diff GMM")
estadd local municipality "Yes": r5
estadd local year "Yes": r5
** プラス有意

** Interaction
xtabond2 compe_rate_adopt c.ln_diff_salary##c.win_ratio_musyozoku_pre L1.compe_rate_adopt ln_population ln_income_per i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(c.ln_diff_salary c.ln_diff_salary#c.win_ratio_musyozoku_pre L.compe_rate_adopt) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) noleveleq robust twostep 
estimates store r6, title("diff GMM")
estadd local municipality "Yes": r6
estadd local year "Yes": r6
** 後半有意; efficiency 向上

margins, dydx(ln_diff_salary) at(win_ratio_musyozoku_pre = (0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1))
marginsplot

xtabond2 compe_rate_adopt c.ln_diff_salary##c.win_ratio_musyozoku_pre ln_population ln_income_per i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(c.ln_diff_salary c.ln_diff_salary#c.win_ratio_musyozoku_pre) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) noleveleq robust twostep

margins, dydx(ln_diff_salary) at(win_ratio_musyozoku_pre = (0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1))

hist win_ratio_musyozoku_pre

esttab r1 r2 r3 r4 r5 r6 using "compe_diffgmm.tex", replace ///
b(3) se(3) star(* 0.10 ** 0.05 *** 0.01) booktabs /// 
drop(*.nendo) nogaps ///
stats(year municipality N, fmt(%9.0f %9.0f %9.0f) labels("年度固定効果" "自治体固定効果" "観測数")) ///
label nolz varwidth(16) modelwidth(13) style(tex)  ///
title(被説明変数: 1議席あたり立候補人数) coeflabels(lnsalary_am_kokuji "対数議員報酬額" ln_diff_salary "報酬額対数差分" L.compe_rate_adopt "1議席あたり立候補人数_1期ラグ" ///
ln_diff_salary#win_ratio_musyozoku_pre "報酬額対数差分 x 前回当選者に占める無所属の割合" c.lnsalary_am_kokuji#c.win_ratio_musyozoku_pre ///
"対数議員報酬額 x 前回当選者に占める無所属の割合" ln_population "対数人口" n_seats_adopt "議席数" population_elderly75_ratio "全人口に占める75歳以上の割合" ///
population_child15_ratio "全人口に占める15歳未満の割合" ln_income_per "納税者1人あたり課税対象所得" ///
ln_all_menseki "対数面積" canlive_ratio_menseki "可住地面積割合" sigaika_ratio_area "市街化区域面積割合" ln_zaiseiryoku ///
"対数財政力指数" win_ratio_musyozoku_pre "前回当選者に占める無所属の割合" ln_staff_all "対数自治体職員数" expired_dummy ///
"任期満了ダミー"  touitsu_2011 "2011年統一選ダミー" touitsu_2015 "2015年統一選ダミー" touitsu_2019 "2019年統一選ダミー") ///
order(lnsalary_am_kokuji c.lnsalary_am_kokuji#c.win_ratio_musyozoku_pre ln_diff_salary c.ln_diff_salary#c.win_ratio_musyozoku_pre L1.compe_rate_adopt) ///
mlabels(, span prefix(\multicolumn{@span}{c}{) suffix(})) ///
prehead("\documentclass[10pt]{jsarticle}" "\pagestyle{empty}" "\usepackage{booktabs}""\usepackage{siunitx}""\usepackage{lscape}" ///
"\usepackage[margin=20truemm]{geometry}""\sisetup{input-symbols = ()}""\begin{document}""\begin{table}\caption{@title}" ///
"\def\sym#1{\ifmmode^{#1}\else\(^{#1}\)\fi}""\begin{center}" ///
"\sisetup{table-space-text-post = \sym{***}}""\begin{tabular}{l*{@M}{llll}}""\toprule") posthead(\midrule) prefoot(\midrule) ///
postfoot("\bottomrule""\end{tabular}""\end{center}""\end{table}""\end{document}")


** System GMM
estimates clear

* system GMM without lag dep; lnsalary_am_kokuji
xtabond2 compe_rate_adopt lnsalary_am_kokuji i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(lnsalary_am_kokuji) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) robust twostep 
estimates store r1, title("sys GMM")
estadd local municipality "Yes": r1
estadd local year "Yes": r1

* system GMM with lag dep; lnsalary_am_kokuji
xtabond2 compe_rate_adopt lnsalary_am_kokuji L1.compe_rate_adopt i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(lnsalary_am_kokuji L.compe_rate_adopt) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) robust twostep
estimates store r2, title("sys GMM")
estadd local municipality "Yes": r2
estadd local year "Yes": r2

** Interaction
xtabond2 compe_rate_adopt c.lnsalary_am_kokuji##c.win_ratio_musyozoku_pre L1.compe_rate_adopt ln_population ln_income_per i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(c.lnsalary_am_kokuji c.lnsalary_am_kokuji#c.win_ratio_musyozoku_pre L.compe_rate_adopt) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) robust twostep 
estimates store r3, title("sys GMM")
estadd local municipality "Yes": r3
estadd local year "Yes": r3

margins, dydx(lnsalary_am_kokuji) at(win_ratio_musyozoku_pre = (0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1))
marginsplot
** 後半有意; efficiency 向上


** system GMM without lag dep; lndiff_am_kokuji

xtabond2 compe_rate_adopt ln_diff_salary i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(ln_diff_salary) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) robust twostep
estimates store r4, title("sys GMM")
estadd local municipality "Yes": r4
estadd local year "Yes": r4
** プラス有意

** system GMM with lag dep; lndiff_am_kokuji
xtabond2 compe_rate_adopt ln_diff_salary L1.compe_rate_adopt i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(ln_diff_salary L.compe_rate_adopt) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) robust twostep 
estimates store r5, title("sys GMM")
estadd local municipality "Yes": r5
estadd local year "Yes": r5
** プラス有意

** Interaction
xtabond2 compe_rate_adopt c.ln_diff_salary##c.win_ratio_musyozoku_pre L1.compe_rate_adopt ln_population ln_income_per i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(c.ln_diff_salary c.ln_diff_salary#c.win_ratio_musyozoku_pre L.compe_rate_adopt) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) robust twostep 
estimates store r6, title("sys GMM")
estadd local municipality "Yes": r6
estadd local year "Yes": r6
** 後半有意; efficiency 向上

margins, dydx(ln_diff_salary) at(win_ratio_musyozoku_pre = (0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1))
marginsplot
** 後半有意; efficiency 向上

esttab r1 r2 r3 r4 r5 r6 using "compe_sysgmm.tex", replace ///
b(3) se(3) star(* 0.10 ** 0.05 *** 0.01) booktabs /// 
drop(*.nendo) nogaps ///
stats(year municipality N, fmt(%9.0f %9.0f %9.0f) labels("年度固定効果" "自治体固定効果" "観測数")) ///
label nolz varwidth(16) modelwidth(13) style(tex)  ///
title(被説明変数: 1議席あたり立候補人数) coeflabels(lnsalary_am_kokuji "対数議員報酬額" ln_diff_salary "報酬額対数差分" L.compe_rate_adopt "1議席あたり立候補人数_1期ラグ" ///
ln_diff_salary#win_ratio_musyozoku_pre "報酬額対数差分 x 前回当選者に占める無所属の割合" c.lnsalary_am_kokuji#c.win_ratio_musyozoku_pre ///
"対数議員報酬額 x 前回当選者に占める無所属の割合" ln_population "対数人口" n_seats_adopt "議席数" population_elderly75_ratio "全人口に占める75歳以上の割合" ///
population_child15_ratio "全人口に占める15歳未満の割合" ln_income_per "納税者1人あたり課税対象所得" ///
ln_all_menseki "対数面積" canlive_ratio_menseki "可住地面積割合" sigaika_ratio_area "市街化区域面積割合" ln_zaiseiryoku ///
"対数財政力指数" win_ratio_musyozoku_pre "前回当選者に占める無所属の割合" ln_staff_all "対数自治体職員数" expired_dummy ///
"任期満了ダミー"  touitsu_2011 "2011年統一選ダミー" touitsu_2015 "2015年統一選ダミー" touitsu_2019 "2019年統一選ダミー") ///
order(lnsalary_am_kokuji c.lnsalary_am_kokuji#c.win_ratio_musyozoku_pre ln_diff_salary c.ln_diff_salary#c.win_ratio_musyozoku_pre L1.compe_rate_adopt) ///
mlabels(, span prefix(\multicolumn{@span}{c}{) suffix(})) ///
prehead("\documentclass[10pt]{jsarticle}" "\pagestyle{empty}" "\usepackage{booktabs}""\usepackage{siunitx}""\usepackage{lscape}" ///
"\usepackage[margin=20truemm]{geometry}""\sisetup{input-symbols = ()}""\begin{document}""\begin{table}\caption{@title}" ///
"\def\sym#1{\ifmmode^{#1}\else\(^{#1}\)\fi}""\begin{center}" ///
"\sisetup{table-space-text-post = \sym{***}}""\begin{tabular}{l*{@M}{llll}}""\toprule") posthead(\midrule) prefoot(\midrule) ///
postfoot("\bottomrule""\end{tabular}""\end{center}""\end{table}""\end{document}")

**squared
estimates clear

reg compe_rate_adopt c.lnsalary_am_kokuji##c.lnsalary_am_kokuji ln_population ln_income_per ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku ln_staff_all win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019, vce(cluster pres_pm_codes)

reg compe_rate_adopt c.lnsalary_am_kokuji##c.lnsalary_am_kokuji ln_population ln_income_per ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku ln_staff_all win_ratio_musyozoku_pre expired_dummy, vce(cluster pres_pm_codes)



xtabond2 compe_rate_adopt c.lnsalary_am_kokuji##c.lnsalary_am_kokuji L1.compe_rate_adopt ln_population ln_income_per i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku ln_staff_all win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019, gmm(c.lnsalary_am_kokuji c.lnsalary_am_kokuji#c.lnsalary_am_kokuji L.compe_rate_adopt) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) noleveleq robust twostep
estimates store r1, title("diff GMM")
estadd local municipality "Yes": r1
estadd local year "Yes": r1 
margins, dydx(lnsalary_am_kokuji) at(lnsalary_am_kokuji = (6.5 7 7.5 8 8.5 9))
marginsplot


xtabond2 compe_rate_adopt c.lnsalary_am_kokuji##c.lnsalary_am_kokuji ln_population ln_income_per i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku ln_staff_all win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019, gmm(c.lnsalary_am_kokuji c.lnsalary_am_kokuji#c.lnsalary_am_kokuji) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) noleveleq robust twostep 
margins, dydx(lnsalary_am_kokuji) at(lnsalary_am_kokuji = (6.5 7 7.5 8 8.5 9))
marginsplot


xtabond2 compe_rate_adopt c.ln_diff_salary##c.ln_diff_salary L1.compe_rate_adopt ln_population ln_income_per i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku ln_staff_all win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019, gmm(c.lnsalary_am_kokuji c.ln_diff_salary#c.ln_diff_salary L.compe_rate_adopt) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) noleveleq robust twostep 
estimates store r2, title("diff GMM")
estadd local municipality "Yes": r2
estadd local year "Yes": r2
margins, dydx(ln_diff_salary) at(ln_diff_salary = (0.5 1 1.5 2 2.5 3 3.5))
marginsplot


xtabond2 compe_rate_adopt c.ln_diff_salary##c.ln_diff_salary ln_population ln_income_per i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku ln_staff_all win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019, gmm(c.lnsalary_am_kokuji c.ln_diff_salary#c.ln_diff_salary) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) noleveleq robust twostep 
margins, dydx(ln_diff_salary) at(ln_diff_salary = (0.5 1 1.5 2 2.5 3 3.5))
marginsplot

xtabond2 compe_rate_adopt c.lnsalary_am_kokuji##c.lnsalary_am_kokuji L1.compe_rate_adopt ln_population ln_income_per i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku ln_staff_all win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019, gmm(c.lnsalary_am_kokuji c.lnsalary_am_kokuji#c.lnsalary_am_kokuji L.compe_rate_adopt) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) robust twostep
estimates store r3, title("sys GMM")
estadd local municipality "Yes": r3
estadd local year "Yes": r3 
margins, dydx(lnsalary_am_kokuji) at(lnsalary_am_kokuji = (6.5 7 7.5 8 8.5 9))
marginsplot


xtabond2 compe_rate_adopt c.lnsalary_am_kokuji##c.lnsalary_am_kokuji ln_population ln_income_per i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku ln_staff_all win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019, gmm(c.lnsalary_am_kokuji c.lnsalary_am_kokuji#c.lnsalary_am_kokuji) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) robust twostep 
margins, dydx(lnsalary_am_kokuji) at(lnsalary_am_kokuji = (6.5 7 7.5 8 8.5 9))
marginsplot

xtabond2 compe_rate_adopt c.ln_diff_salary##c.ln_diff_salary L1.compe_rate_adopt ln_population ln_income_per i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku ln_staff_all win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019, gmm(c.lnsalary_am_kokuji c.ln_diff_salary#c.ln_diff_salary L.compe_rate_adopt) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) robust twostep 
estimates store r4, title("sys GMM")
estadd local municipality "Yes": r4
estadd local year "Yes": r4
margins, dydx(ln_diff_salary) at(ln_diff_salary = (0.5 1 1.5 2 2.5 3 3.5))
marginsplot


xtabond2 compe_rate_adopt c.ln_diff_salary##c.ln_diff_salary ln_population ln_income_per i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku ln_staff_all win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019, gmm(c.lnsalary_am_kokuji c.ln_diff_salary#c.ln_diff_salary) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) robust twostep 
margins, dydx(ln_diff_salary) at(ln_diff_salary = (0.5 1 1.5 2 2.5 3 3.5))
marginsplot


xtreg compe_rate_adopt c.lnsalary_am_kokuji##c.lnsalary_am_kokuji ln_population ln_income_per i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku ln_staff_all win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019,fe vce(cluster pres_pm_codes)
estimates store r5, title("FE")
estadd local municipality "Yes": r5
estadd local year "Yes": r5
margins, dydx(lnsalary_am_kokuji) at(lnsalary_am_kokuji = (6.5 7 7.5 8 8.5 9))
marginsplot

xtreg compe_rate_adopt c.ln_diff_salary##c.ln_diff_salary ln_population ln_income_per i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku ln_staff_all win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019,fe vce(cluster pres_pm_codes)
margins, dydx(ln_diff_salary) at(ln_diff_salary = (0.5 1 1.5 2 2.5 3 3.5))
marginsplot

xtpoisson compe_rate_minus1_adj c.lnsalary_am_kokuji##c.lnsalary_am_kokuji ln_population ln_income_per i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku ln_staff_all win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019,fe vce(robust)
estimates store r6, title("PPMLFE")
estadd local municipality "Yes": r6
estadd local year "Yes": r6
margins, dydx(lnsalary_am_kokuji) at(lnsalary_am_kokuji = (6.5 7 7.5 8 8.5 9))
marginsplot

xtpoisson compe_rate_minus1_adj c.ln_diff_salary##c.ln_diff_salary ln_population ln_income_per i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku ln_staff_all win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019,fe vce(robust)
margins, dydx(ln_diff_salary) at(ln_diff_salary = (0.5 1 1.5 2 2.5 3 3.5))
marginsplot

esttab r5 r6 r1 r2 r3 r4 using "compe_squared_gmm.tex", replace ///
b(3) se(3) star(* 0.10 ** 0.05 *** 0.01) booktabs /// 
drop(*.nendo) nogaps ///
stats(year municipality N, fmt(%9.0f %9.0f %9.0f) labels("年度固定効果" "自治体固定効果" "観測数")) ///
label nolz varwidth(16) modelwidth(13) style(tex)  ///
title(被説明変数: 1議席あたり立候補人数) coeflabels(lnsalary_am_kokuji "対数議員報酬額" ln_diff_salary "報酬額対数差分" L.compe_rate_adopt "1議席あたり立候補人数_1期ラグ" ///
c.ln_diff_salary#c.ln_diff_salary "報酬額対数差分 2乗" c.lnsalary_am_kokuji#c.lnsalary_am_kokuji ///
"対数議員報酬額 2乗" ln_population "対数人口" n_seats_adopt "議席数" population_elderly75_ratio "全人口に占める75歳以上の割合" ///
population_child15_ratio "全人口に占める15歳未満の割合" ln_income_per "納税者1人あたり課税対象所得" ///
ln_all_menseki "対数面積" canlive_ratio_menseki "可住地面積割合" sigaika_ratio_area "市街化区域面積割合" ln_zaiseiryoku ///
"対数財政力指数" win_ratio_musyozoku_pre "前回当選者に占める無所属の割合" ln_staff_all "対数自治体職員数" expired_dummy ///
"任期満了ダミー"  touitsu_2011 "2011年統一選ダミー" touitsu_2015 "2015年統一選ダミー" touitsu_2019 "2019年統一選ダミー") ///
order(lnsalary_am_kokuji c.lnsalary_am_kokuji#c.lnsalary_am_kokuji ln_diff_salary c.ln_diff_salary#c.ln_diff_salary L.compe_rate_adopt) ///
mlabels(, span prefix(\multicolumn{@span}{c}{) suffix(})) ///
prehead("\documentclass[10pt]{jsarticle}" "\pagestyle{empty}" "\usepackage{booktabs}""\usepackage{siunitx}""\usepackage{lscape}" ///
"\usepackage[margin=20truemm]{geometry}""\sisetup{input-symbols = ()}""\begin{document}""\begin{table}\caption{@title}" ///
"\def\sym#1{\ifmmode^{#1}\else\(^{#1}\)\fi}""\begin{center}" ///
"\sisetup{table-space-text-post = \sym{***}}""\begin{tabular}{l*{@M}{llll}}""\toprule") posthead(\midrule) prefoot(\midrule) ///
postfoot("\bottomrule""\end{tabular}""\end{center}""\end{table}""\end{document}")






