tsset pres_pm_codes year

**touitsu_ele_dummy each

gen touitsu_2007 = 0
replace touitsu_2007 = 1 if ((touitsu_ele_dummy == 1)&(kokuji_nendo == 2007))

gen touitsu_2011 = 0
replace touitsu_2011 = 1 if ((touitsu_ele_dummy == 1)&(kokuji_nendo == 2011))

gen touitsu_2015 = 0
replace touitsu_2015 = 1 if ((touitsu_ele_dummy == 1)&(kokuji_nendo == 2015))

gen touitsu_2019 = 0
replace touitsu_2019 = 1 if ((touitsu_ele_dummy == 1)&(kokuji_nendo == 2019))

**nendo_dummies
tabulate nendo, generate(nendo)

* log etc
gen lnsalary_am_kokuji = ln(salary_am_kokuji)
gen lnsalary_am_start = ln(salary_am_start)
gen ln_mean_ruiji_1yago = ln(mean_salary_ruiji_1yago)
gen ln_mean_ruiji_1yago_kokuji = ln(mean_salary_ruiji_1yago_kokuji)


gen ln_population = log(population)
gen ln_income_per = log(income_per_syotokuwari)
gen ln_all_menseki = log(all_menseki)

gen ln_staff_all = log(n_staff_all)

gen salary_12month = 12 * salary_am_kokuji
gen ln_diff_salary = log(salary_12month) - log(income_per_syotokuwari)
gen ratio_salary = salary_12month/income_per_syotokuwari
gen persentage_salary = (salary_12month - income_per_syotokuwari)/income_per_syotokuwari

gen compe_rate_minus1 = compe_rate_adopt - 1

gen compe_rate_minus1_adj = compe_rate_minus1

replace compe_rate_minus1_adj = 0 if compe_rate_minus1_adj < 0

gen dummy_jyorei = .
replace dummy_jyorei = 0 if count_jyorei == 0
replace dummy_jyorei = 1 if count_jyorei > 0

gen sigaika_ratio_area = sigaika_area / all_menseki
replace sigaika_ratio_area = 1 if sigaika_ratio_area > 1

gen ln_zaiseiryoku = log(zaiseiryoku_index)


hist count_jyorei

sum lnsalary_am_start ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki zaiseiryoku_index sigaika_ratio_area win_ratio_musyozoku expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 n_staff_all

* jyorei

** poisson
poisson count_jyorei lnsalary_am_start, vce(robust)

poisson count_jyorei lnsalary_am_start ln_population, vce(robust)
poisson count_jyorei lnsalary_am_kokuji ln_population, vce(robust)
poisson count_jyorei lnsalary_am_kokuji lnsalary_am_start ln_population, vce(robust)

poisson count_jyorei lnsalary_am_start ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 n_staff_all, vce(robust)

poisson count_jyorei lnsalary_am_kokuji lnsalary_am_start ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 n_staff_all, vce(robust)

xtpoisson count_jyorei lnsalary_am_start  i.nendo, fe vce(robust)
xtpoisson count_jyorei lnsalary_am_kokuji i.nendo, fe vce(robust)
xtpoisson count_jyorei lnsalary_am_start lnsalary_am_kokuji i.nendo, fe vce(robust)
xtpoisson count_jyorei lnsalary_am_start ln_population i.nendo, fe vce(robust)

xtpoisson count_jyorei lnsalary_am_start ln_population n_seats_adopt i.nendo, fe vce(robust)
xtpoisson count_jyorei lnsalary_am_start ln_population n_seats_adopt population_elderly75_ratio i.nendo, fe vce(robust)
xtpoisson count_jyorei lnsalary_am_start ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio i.nendo, fe vce(robust)
xtpoisson count_jyorei lnsalary_am_start ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per i.nendo, fe vce(robust)
xtpoisson count_jyorei lnsalary_am_start ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki i.nendo, fe vce(robust) 
** 上はダメ

xtpoisson count_jyorei lnsalary_am_start ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per canlive_ratio_menseki  i.nendo, fe vce(robust)
xtpoisson count_jyorei lnsalary_am_start ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per canlive_ratio_menseki  sigaika_ratio_area i.nendo, fe vce(robust)
xtpoisson count_jyorei lnsalary_am_start ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per canlive_ratio_menseki  sigaika_ratio_area zaiseiryoku_index i.nendo, fe vce(robust)
xtpoisson count_jyorei lnsalary_am_start ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per canlive_ratio_menseki  sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku_pre i.nendo, fe vce(robust)
**ここで符号が変化
xtpoisson count_jyorei lnsalary_am_start ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per canlive_ratio_menseki  sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku_pre n_staff_all i.nendo, fe vce(robust)
xtpoisson count_jyorei lnsalary_am_start ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per canlive_ratio_menseki  sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku_pre n_staff_all expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 i.nendo, fe vce(robust)

xtpoisson count_jyorei lnsalary_am_start ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 n_staff_all, fe vce(robust) 


xtpoisson count_jyorei lnsalary_am_start ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku_pre expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 i.nendo n_staff_all, fe vce(robust) 


** そもそも全て0の自治体を省いているので、話にならない

**pooled poisson

poisson count_jyorei lnsalary_am_start, vce(cluster pres_pm_codes)

poisson count_jyorei lnsalary_am_start ln_population, vce(cluster pres_pm_codes)
poisson count_jyorei lnsalary_am_kokuji ln_population, vce(cluster pres_pm_codes)
poisson count_jyorei lnsalary_am_kokuji lnsalary_am_start ln_population, vce(cluster pres_pm_codes)

poisson count_jyorei lnsalary_am_start ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 n_staff_all, vce(cluster pres_pm_codes)

poisson count_jyorei lnsalary_am_kokuji ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 n_staff_all, vce(cluster pres_pm_codes)

poisson count_jyorei lnsalary_am_kokuji lnsalary_am_start ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 n_staff_all, vce(cluster pres_pm_codes)

poisson count_jyorei lnsalary_am_start ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 n_staff_all i.nendo  vce(cluster pres_pm_codes)

poisson count_jyorei lnsalary_am_start ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 n_staff_all i.nendo i.pref_id, vce(cluster pres_pm_codes)

encode time_muni_kind, generate(muni_type)

poisson count_jyorei lnsalary_am_start ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 n_staff_all i.nendo i.pref_id i.muni_type, vce(robust)

poisson count_jyorei lnsalary_am_start ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 n_staff_all i.nendo i.pref_id i.muni_type, vce(cluster pres_pm_codes)

** dummy_jyorei
reg dummy_jyorei lnsalary_am_start, vce(cluster pres_pm_codes)
reg dummy_jyorei lnsalary_am_start ln_population, vce(cluster pres_pm_codes)
reg dummy_jyorei lnsalary_am_start ln_population n_seats_adopt population_elderly75_ratio, vce(cluster pres_pm_codes)
reg dummy_jyorei lnsalary_am_start ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio, vce(cluster pres_pm_codes)
reg dummy_jyorei lnsalary_am_start ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per, vce(cluster pres_pm_codes)
reg dummy_jyorei lnsalary_am_start ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki, vce(cluster pres_pm_codes)
reg dummy_jyorei lnsalary_am_start ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki, vce(cluster pres_pm_codes)
reg dummy_jyorei lnsalary_am_start ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area, vce(cluster pres_pm_codes)
reg dummy_jyorei lnsalary_am_start ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index, vce(cluster pres_pm_codes)
reg dummy_jyorei lnsalary_am_start ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku, vce(cluster pres_pm_codes)
reg dummy_jyorei lnsalary_am_start ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku n_staff_all , vce(cluster pres_pm_codes)
reg dummy_jyorei lnsalary_am_start ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku n_staff_all expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019, vce(cluster pres_pm_codes)
reg dummy_jyorei lnsalary_am_start ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku n_staff_all expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019, vce(cluster pres_pm_codes)
reg dummy_jyorei lnsalary_am_start ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku n_staff_all expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 i.nendo, vce(cluster pres_pm_codes)
reg dummy_jyorei lnsalary_am_start ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku n_staff_all expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 i.nendo i.pref_id, vce(cluster pres_pm_codes)
reg dummy_jyorei lnsalary_am_start ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku n_staff_all expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 i.nendo i.pref_id i.muni_type, vce(cluster pres_pm_codes) 
** 来た!

probit dummy_jyorei lnsalary_am_start ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku n_staff_all expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 i.nendo i.pref_id i.muni_type, vce(cluster pres_pm_codes) 
margins, dydx(lnsalary_am_start) at (lnsalary_am_start = (7 8 9))

xtreg dummy_jyorei lnsalary_am_start, fe vce(cluster pres_pm_codes)
xtreg dummy_jyorei lnsalary_am_start i.nendo, fe vce(cluster pres_pm_codes)
xtreg dummy_jyorei lnsalary_am_start i.nendo, fe vce(cluster pres_pm_codes)
xtreg dummy_jyorei lnsalary_am_start ln_population i.nendo, fe vce(cluster pres_pm_codes)
xtreg dummy_jyorei lnsalary_am_start ln_population n_seats_adopt i.nendo, fe vce(cluster pres_pm_codes)
xtreg dummy_jyorei lnsalary_am_start ln_population n_seats_adopt population_elderly75_ratio i.nendo, fe vce(cluster pres_pm_codes)
xtreg dummy_jyorei lnsalary_am_start ln_population n_seats_adopt population_child15_ratio i.nendo, fe vce(cluster pres_pm_codes)
xtreg dummy_jyorei lnsalary_am_start ln_population n_seats_adopt population_child15_ratio ln_income_per i.nendo, fe vce(cluster pres_pm_codes)
xtreg dummy_jyorei lnsalary_am_start ln_population n_seats_adopt population_child15_ratio population_elderly75_ratio ln_income_per i.nendo, fe vce(cluster pres_pm_codes)
xtreg dummy_jyorei lnsalary_am_start ln_population n_seats_adopt population_child15_ratio population_elderly75_ratio ln_income_per ln_all_menseki i.nendo, fe vce(cluster pres_pm_codes)
xtreg dummy_jyorei lnsalary_am_start ln_population n_seats_adopt population_child15_ratio population_elderly75_ratio ln_income_per ln_all_menseki canlive_ratio_menseki i.nendo, fe vce(cluster pres_pm_codes)
xtreg dummy_jyorei lnsalary_am_start ln_population n_seats_adopt population_child15_ratio population_elderly75_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area i.nendo, fe vce(cluster pres_pm_codes)
xtreg dummy_jyorei lnsalary_am_start ln_population n_seats_adopt population_child15_ratio population_elderly75_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index i.nendo, fe vce(cluster pres_pm_codes)
xtreg dummy_jyorei lnsalary_am_start ln_population n_seats_adopt population_child15_ratio population_elderly75_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku i.nendo, fe vce(cluster pres_pm_codes)
xtreg dummy_jyorei lnsalary_am_start ln_population n_seats_adopt population_child15_ratio population_elderly75_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku n_staff_all i.nendo, fe vce(cluster pres_pm_codes)
xtreg dummy_jyorei lnsalary_am_start ln_population n_seats_adopt population_child15_ratio population_elderly75_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku n_staff_all expired_dummy i.nendo, fe vce(cluster pres_pm_codes)
xtreg dummy_jyorei lnsalary_am_start ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku n_staff_all expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 i.nendo, fe vce(cluster pres_pm_codes)
xtreg dummy_jyorei lnsalary_am_start ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku n_staff_all expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 i.muni_type i.nendo, fe vce(cluster pres_pm_codes)

xtreg dummy_jyorei lnsalary_am_kokuji ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku n_staff_all expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 i.muni_type i.nendo, fe vce(cluster pres_pm_codes)

xtreg dummy_jyorei lnsalary_am_start lnsalary_am_kokuji ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku n_staff_all expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 i.muni_type i.nendo, fe vce(cluster pres_pm_codes)

corr dummy_jyorei lnsalary_am_start lnsalary_am_kokuji ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku n_staff_all expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 

xtreg dummy_jyorei lnsalary_am_start ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku n_staff_all expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 i.nendo ,fe vce(cluster pres_pm_codes)

xtreg dummy_jyorei lnsalary_am_start ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku ln_staff_all expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 i.nendo ,fe vce(cluster pres_pm_codes)

xtreg dummy_jyorei c.lnsalary_am_start##c.win_ratio_musyozoku ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index ln_staff_all expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 i.nendo ,fe vce(cluster pres_pm_codes)

xtreg dummy_jyorei c.lnsalary_am_start##c.ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku ln_staff_all expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 i.nendo ,fe vce(cluster pres_pm_codes)

xtreg dummy_jyorei c.lnsalary_am_start##c.ln_income_per ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku n_staff_all expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 i.nendo ,fe vce(cluster pres_pm_codes)

xtreg dummy_jyorei c.lnsalary_am_start##c.ln_staff_all ln_income_per ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 i.nendo ,fe vce(cluster pres_pm_codes)

margins, dydx(lnsalary_am_start) at(ln_staff_all  == (4 6 8 10))

xtreg dummy_jyorei c.lnsalary_am_start##c.zaiseiryoku_index ln_income_per ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku ln_staff_all expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 i.nendo ,fe vce(cluster pres_pm_codes)

margins, dydx(lnsalary_am_start) at(zaiseiryoku_index  == (0.2 0.4 0.6 0.8 1 1.5 2 2.5))

xtreg dummy_jyorei c.lnsalary_am_start##c.zaiseiryoku_index ln_income_per ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku ln_staff_all expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 i.nendo ,fe vce(cluster pres_pm_codes)

xtlogit dummy_jyorei lnsalary_am_start ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku n_staff_all expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 i.nendo i.muni_type, fe vce()
** ダメ

xtreg dummy_jyorei c.lnsalary_am_start ln_income_per ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku ln_staff_all expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 i.nendo age_mean_wins ratio_women_wins_adopt,fe vce(cluster pres_pm_codes)

xtreg dummy_jyorei lnsalary_am_start ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku n_staff_all expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 i.nendo i.muni_type, vce(cluster pres_pm_codes)

** lnsalary_am_kokuji 
xtreg dummy_jyorei c.lnsalary_am_kokuji ln_income_per ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku ln_staff_all expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 i.nendo ,fe vce(cluster pres_pm_codes)

xtreg dummy_jyorei c.lnsalary_am_kokuji ln_income_per ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku ln_staff_all expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 i.nendo age_mean_wins ,fe vce(cluster pres_pm_codes)

xtreg dummy_jyorei c.lnsalary_am_kokuji ln_income_per ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku ln_staff_all expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 i.nendo age_mean_wins ratio_women_wins_adopt,fe vce(cluster pres_pm_codes)

xtreg dummy_jyorei c.lnsalary_am_kokuji ln_income_per ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku ln_staff_all expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 i.nendo age_mean_wins ratio_women_wins_adopt,fe vce(cluster pres_pm_codes)

xtreg dummy_jyorei c.lnsalary_am_kokuji##c.lnsalary_am_kokuji ln_income_per ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku ln_staff_all expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 i.nendo age_mean_wins ratio_women_wins_adopt,fe vce(cluster pres_pm_codes)

** IV; lnsalary_am_start 

ivregress 2sls dummy_jyorei (lnsalary_am_start = ln_mean_ruiji_1yago) ln_income_per ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku ln_staff_all expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 i.nendo i.muni_type i.pref_id ,vce(cluster pres_pm_codes)

xtivreg dummy_jyorei (lnsalary_am_start = ln_mean_ruiji_1yago) ln_income_per ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku ln_staff_all expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 i.nendo ,fe vce(cluster pres_pm_codes)

xtivreg dummy_jyorei (lnsalary_am_start = ln_mean_ruiji_1yago) ln_income_per ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku ln_staff_all expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 i.nendo ,fd vce(cluster pres_pm_codes)

ivregress 2sls D.dummy_jyorei (D.lnsalary_am_start = L.ln_mean_ruiji_1yago) D.(ln_income_per ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku ln_staff_all expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 nendo2-nendo8) , vce(cluster pres_pm_codes)
estat first

ivregress 2sls D.dummy_jyorei (D.lnsalary_am_start = L.lnsalary_am_start) D.(ln_income_per ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku ln_staff_all expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 nendo2-nendo8) , vce(cluster pres_pm_codes)
estat first

ivregress 2sls D.dummy_jyorei (D.lnsalary_am_start = L.ln_mean_ruiji_1yago L.lnsalary_am_start) D.(ln_income_per ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku ln_staff_all expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 nendo2-nendo8) , vce(cluster pres_pm_codes)
estat first

ivregress 2sls D.dummy_jyorei (D.lnsalary_am_start LD.dummy_jyorei = L.lnsalary_am_start L2.dummy_jyorei) D.(ln_income_per ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku ln_staff_all expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 nendo2-nendo8) , vce(cluster pres_pm_codes)
estat first

** Arellano; lnsalary_am_start 

abbond2 dummy_jyorei lnsalary_am_start ln_income_per ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku ln_staff_all expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 i.nendo ,fe vce(cluster pres_pm_codes)

xtabond2 dummy_jyorei lnsalary_am_start i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index cand_ratio_musyozoku expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(lnsalary_am_start) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index cand_ratio_musyozoku expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) nolevel robust twostep small

xtabond2 dummy_jyorei lnsalary_am_start i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index cand_ratio_musyozoku expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(lnsalary_am_start) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index cand_ratio_musyozoku expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) nolevel robust twostep small

xtabond2 dummy_jyorei lnsalary_am_start i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index cand_ratio_musyozoku expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(lnsalary_am_start, eq(level)) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index cand_ratio_musyozoku expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) nolevel robust twostep small
**死んだよ

xtabond2 dummy_jyorei lnsalary_am_start i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index cand_ratio_musyozoku expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(lnsalary_am_start, eq(both)) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index cand_ratio_musyozoku expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) nolevel robust twostep 
** 解釈不能

* IV; lnsalary_am_kokuji
ivregress 2sls dummy_jyorei (lnsalary_am_kokuji = ln_mean_ruiji_1yago_kokuji) ln_income_per ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku ln_staff_all expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 i.nendo i.muni_type i.pref_id ,vce(cluster pres_pm_codes)

xtivreg dummy_jyorei (lnsalary_am_kokuji = ln_mean_ruiji_1yago_kokuji) ln_income_per ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku ln_staff_all expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 i.nendo ,fe vce(cluster pres_pm_codes)

ivregress 2sls D.dummy_jyorei (D.lnsalary_am_kokuji = L.ln_mean_ruiji_1yago_kokuji) D.(ln_income_per ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku ln_staff_all expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 nendo2-nendo8) , vce(cluster pres_pm_codes)
estat first 
*weak 

ivregress 2sls D.dummy_jyorei (D.lnsalary_am_kokuji = D.ln_mean_ruiji_1yago_kokuji) D.(ln_income_per ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku ln_staff_all expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 nendo2-nendo8) , vce(cluster pres_pm_codes)
estat first 

ivregress 2sls D.dummy_jyorei (D.lnsalary_am_start LD.dummy_jyorei = L.ln_mean_ruiji_1yago_kokuji L2.dummy_jyorei) D.(ln_income_per ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index win_ratio_musyozoku ln_staff_all expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 nendo2-nendo8) , vce(cluster pres_pm_codes)
estat first
** 解釈不能

xtabond2 dummy_jyorei lnsalary_am_start L1.dummy_jyorei i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku  expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(lnsalary_am_start L.dummy_jyorei) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) nolevel robust twostep 
*プラス有意

xtabond2 dummy_jyorei lnsalary_am_start L1.dummy_jyorei i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku  expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(lnsalary_am_start L.dummy_jyorei) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) robust twostep 
age_mean_cand  ratio_women_cand_adopt cand_ratio_musyozoku

xtabond2 dummy_jyorei lnsalary_am_start L1.dummy_jyorei i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku  expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all age_mean_wins ratio_women_wins_adopt win_ratio_musyozoku compe_rate_adopt, gmm(lnsalary_am_start L.dummy_jyorei) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area ln_zaiseiryoku expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all age_mean_wins ratio_women_wins_adopt win_ratio_musyozoku compe_rate_adopt) nolevel robust twostep 


xtabond2 dummy_jyorei lnsalary_am_start L1.dummy_jyorei i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index cand_ratio_musyozoku expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all, gmm(lnsalary_am_start L.dummy_jyorei) ivstyle(i.nendo ln_population n_seats_adopt population_elderly75_ratio population_child15_ratio ln_income_per ln_all_menseki canlive_ratio_menseki sigaika_ratio_area zaiseiryoku_index cand_ratio_musyozoku expired_dummy touitsu_2007 touitsu_2011 touitsu_2015 touitsu_2019 ln_staff_all) nolevel robust twostep 




